defmodule TestBed.Repo.Migrations.AddCustomerTenant do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:customers) do
      add :tenant, :text
    end
  end

  def down do
    alter table(:customers) do
      remove :tenant
    end
  end
end
